user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:home }

user_dashboard:
    path:   /dashboard
    defaults: { _controller: UserBundle:Default:dashboard }

profile_details:
    path:   /profile/details
    defaults: { _controller: UserBundle:ProfileDetails:profiledetails }